name: Deploy to S3

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: NodeJs Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create S3 Bucket with Website Configuration
        run: |
          aws s3api create-bucket \
            --bucket primuslearning-github-actions-website \
            --region us-east-1

          aws s3api put-public-access-block \
            --bucket primuslearning-github-actions-website \
            --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

          aws s3api put-bucket-website \
            --bucket primuslearning-github-actions-website \
            --website-configuration '{
                "IndexDocument": {
                    "Suffix": "index.html"
                },
                "ErrorDocument": {
                    "Key": "error.html"
                }
            }'

          # Add a bucket policy to allow public read access
          aws s3api put-bucket-policy \
            --bucket primuslearning-github-actions-website \
            --policy '{
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": "*",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::primuslearning-github-actions-website/*"
                    }
                ]
            }'

      - name: Deploy to S3
        run: aws s3 sync build s3://thermalmachine --delete
